default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: miaowster_test

development:
  <<: *default
  database: miaowster_development

production:
  <<: *default
  database: miaowster_production
  username: miaowster
  password: <%= ENV['MIAOWSTER_DATABASE_PASSWORD'] %>
